language: go

os:
  - linux
  - osx

branches:
  only:
    - dev.remote

# don't run go get -t ./...
# ThreadSanitizer fix:
#   https://github.com/google/sanitizers/wiki/ThreadSanitizerCppManual#faq
#   https://github.com/ruslo/hunter/issues/718#issuecomment-290610583
install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install clang-3.8; fi

script:
  - cd src
  - GOROOT_BOOTSTRAP=$GOROOT ./all.bash
