language: go

os:
  - linux
  - osx

addons:
  apt:
    packages:
      - clang

branches:
  only:
    - dev.remote

# don't run go get -t ./...
install: true

script:
  - cd src
  - GOROOT_BOOTSTRAP=$GOROOT ./all.bash
