// Code generated by protoc-gen-go.
// source: remoteapi.proto
// DO NOT EDIT!

/*
Package api is a generated protocol buffer package.

It is generated from these files:
	remoteapi.proto

It has these top-level messages:
	AllocRequest
	AllocResponse
*/
package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AllocRequest struct {
	Size uint64 `protobuf:"varint,1,opt,name=size" json:"size,omitempty"`
}

func (m *AllocRequest) Reset()                    { *m = AllocRequest{} }
func (m *AllocRequest) String() string            { return proto.CompactTextString(m) }
func (*AllocRequest) ProtoMessage()               {}
func (*AllocRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *AllocRequest) GetSize() uint64 {
	if m != nil {
		return m.Size
	}
	return 0
}

type AllocResponse struct {
	Id uint64 `protobuf:"fixed64,1,opt,name=id" json:"id,omitempty"`
}

func (m *AllocResponse) Reset()                    { *m = AllocResponse{} }
func (m *AllocResponse) String() string            { return proto.CompactTextString(m) }
func (*AllocResponse) ProtoMessage()               {}
func (*AllocResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *AllocResponse) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func init() {
	proto.RegisterType((*AllocRequest)(nil), "api.AllocRequest")
	proto.RegisterType((*AllocResponse)(nil), "api.AllocResponse")
}

func init() { proto.RegisterFile("remoteapi.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 143 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x2f, 0x4a, 0xcd, 0xcd,
	0x2f, 0x49, 0x4d, 0x2c, 0xc8, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4e, 0x2c, 0xc8,
	0x54, 0x52, 0xe2, 0xe2, 0x71, 0xcc, 0xc9, 0xc9, 0x4f, 0x0e, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e,
	0x11, 0x12, 0xe2, 0x62, 0x29, 0xce, 0xac, 0x4a, 0x95, 0x60, 0x54, 0x60, 0xd4, 0x60, 0x09, 0x02,
	0xb3, 0x95, 0xe4, 0xb9, 0x78, 0xa1, 0x6a, 0x8a, 0x0b, 0xf2, 0xf3, 0x8a, 0x53, 0x85, 0xf8, 0xb8,
	0x98, 0x32, 0x53, 0xc0, 0x4a, 0xd8, 0x82, 0x98, 0x32, 0x53, 0x8c, 0xec, 0xb9, 0x78, 0x83, 0xc0,
	0x86, 0x07, 0x95, 0xe6, 0x95, 0x64, 0xe6, 0xa6, 0x0a, 0xe9, 0x71, 0xb1, 0x82, 0x75, 0x08, 0x09,
	0xea, 0x81, 0xec, 0x43, 0xb6, 0x41, 0x4a, 0x08, 0x59, 0x08, 0x62, 0x60, 0x12, 0x1b, 0xd8, 0x45,
	0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x40, 0x7c, 0x65, 0x2e, 0xa4, 0x00, 0x00, 0x00,
}
